### PR TITLE
Fixes there is no s:sub

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by zArubaru** [comment]
Thanks, switched to your branch and this fixed my issues atleast:
`Plug 'LinuxSuRen/fugitive-bitbucket.vim', { 'branch': 'fix/sub' }`

**Comment by LinuxSuRen** [comment]
I didn't dig it too deeply. It just works for me.

**Comment by Scuilion** [comment]
`s:sub` is a function declared in the vim-fugitive plugin (which is a requirement for this plugin).

https://github.com/tpope/vim-fugitive/blob/9b6a24b13166feee0cc83e2cc40e2ddb31bcc2a1/autoload/fugitive.vim#L21

**Comment by mark2185** [comment]
This is already in `master`, closing.

**Pull request closed without merging**
