### PR TITLE
Fix 404 when using :GBrowse in normal mode

### LINKED ISSUE #18: Does not work with branches containing slashes "/"
If a branch contains a slash, :Gbrowse leads to a 404 page.

This is because of a bitbucket api limitation: https://jira.atlassian.com/browse/BCLOUD-9969?focusedCommentId=2598330&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2598330

There is no straightforward fix for that. Escaping slashes with %2F does not work.
The only fix I see would be to replace the branch name by the commit hash.

### PR DESCRIPTION
**Pull request by mark2185**
This fixes #18 .

### CODE REVIEW

**Comment by panosl** [comment]
Thanks @mark2185, merged in my fork!

**Comment by tommcdo** [comment]
Looks good to me!

**Comment by tommcdo** [comment]
@mark2185 @panosl Would either of you be interested in becoming a maintainer of this project? I haven't been using Bitbucket in quite some time, and I'd rather have someone else take the reigns than let it become stale.

**Comment by mark2185** [comment]
Sure, why not :)

**Comment by panosl** [comment]
Thanks for your work @tommcdo, hopefully @mark2185 can pick up your work and keep it fresh!

**Pull request merged**
