### PR TITLE
Use only tail of path in line number anchor

### PR DESCRIPTION
**Pull request by tvjg**
This should wrap up the work started in #3 . Thanks for the pointer to `fnamemodify`.

### CODE REVIEW

**Comment by tommcdo** [comment]
`:Gbrowse` does work from other types of Git objects, like a commit. Try pressing `o` on a commit hash from the `:Gblame` window, then use `:Gbrowse` on a line there. For that particular case, it only links to the commit (no line number included), so we'd be safe in this instance. I'd be interested in looking for other cases where the fugitive might link to a particular line of some multi-file object.

Can you do a bit of legwork to see if there are other cases we might need to handle?

**Comment by tvjg** [comment]
When I was trying to figure out what all the conditional branches did in `fubitive.vim`, I actually checked that same `:Gblame` case. Use that feature all the time at work. I'll poke around the `fugitive` manual and see if anything else jumps out.

**Comment by tvjg** [comment]
I reviewed the `fugitive` docs and the VimCasts on it. Didn't run across any unexpected cases. If something crops up, I would be happy to patch. I did run across [this](https://bitbucket.org/site/master/issues/10622/url-link-to-multiple-lines-with-cl-xx-yy) though. Looks like Bitbucket has added line number ranges finally. I'll try to open up another PR for that when I have some time.

**Comment by tommcdo** [comment]
Sounds good. Thanks again :)

**Pull request merged**
